BEGIN;

DROP TABLE IF EXISTS map_position;
DROP TABLE IF EXISTS map_position_2d;

CREATE TABLE map_position (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	x REAL NOT NULL,
    y REAL NOT NULL,
    z REAL NOT NULL
);

CREATE TABLE map_position_2d (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	x REAL NOT NULL,
    y REAL NOT NULL
);

COMMIT;